(()=>{"use strict";
const dict={
en:{home:"Home",about:"About Us",services:"Our Services",industries:"Industries",safety:"Safety",contact:"Contact",touch:"Get in Touch",industrialSolutions:"INDUSTRIAL SOLUTIONS",heroTitle:"NAHDAT AL MUSTAQBIL<br><em>INDUSTRIAL GASES</em>",heroSub:"Reliable Industrial Solutions for a Stronger Tomorrow",heroText:"Supporting industrial operations with a focus on reliability, safety and professional service across Saudi Arabia.",ourServices:"Our Services",contactUs:"Contact Us",applications:"Industrial Applications",applicationsSub:"Supporting diverse industries",safeReliable:"Safety & Reliability",safeReliableSub:"Focused on every operation",trustedSupport:"Trusted Support",trustedSupportSub:"Built around your requirements",dammam:"Dammam, Kingdom of Saudi Arabia",scroll:"SCROLL TO EXPLORE",who:"WHO WE ARE",aboutTitle:"Industrial capability.<br><span>Modern execution.</span>",aboutText:"Nahdat Al Mustaqbil Industrial Gases supports industrial requirements through dependable supply, professional coordination and a safety-first approach.",responsiveSupply:"Responsive Supply",responsiveText:"Solutions structured around operational needs and continuity.",industrialFocus:"Industrial Focus",focusText:"Built for demanding environments, projects and production operations.",professionalSupport:"Professional Support",supportText:"Clear coordination from enquiry through delivery and follow-up.",what:"WHAT WE DO",servicesTitle:"Solutions that move<br><span>industry forward.</span>",gasSolutions:"Industrial Gas Solutions",gasText:"Professional solutions for industrial operations and project requirements.",supplyDistribution:"Supply & Distribution",supplyText:"Organized supply and distribution support for business and industrial customers.",industrialApps:"Industrial Applications",appsText:"Support for fabrication, construction, manufacturing and related industrial activities.",technicalSupport:"Technical Support",technicalText:"Practical coordination and assistance focused on safe, efficient operations.",built:"BUILT FOR INDUSTRY",industriesTitle:"One partner.<br><span>Multiple applications.</span>",fabrication:"Fabrication & Welding",construction:"Construction",manufacturing:"Manufacturing",energy:"Energy & Projects",safetyTitle:"Designed around<br><span>responsible operations.</span>",safetyText:"From handling and coordination to industrial supply support, safety and operational discipline remain central to how we work.",location:"OUR LOCATION · DAMMAM",a1:"Building No. <strong>7036</strong>, Street <strong>45</strong>",a2:"Secondary No. <strong>3313</strong>",a3:"Al Khadamat Al Musanida Dist.",a4:"Postal Code <strong>34354</strong>",build:"LET'S BUILD FORWARD",finalTitle:"Industrial solutions.<br><span>Future focused.</span>",back:"Back to top ↑",company:"NAHDAT AL MUSTAQBIL INDUSTRIAL GASES"},
ar:{home:"الرئيسية",about:"من نحن",services:"خدماتنا",industries:"القطاعات",safety:"السلامة",contact:"اتصل بنا",touch:"تواصل معنا",industrialSolutions:"حلول صناعية",heroTitle:"نهضة المستقبل<br><em>للغازات الصناعية</em>",heroSub:"حلول صناعية موثوقة لمستقبل أقوى",heroText:"ندعم العمليات الصناعية مع التركيز على الموثوقية والسلامة والخدمة المهنية في جميع أنحاء المملكة العربية السعودية.",ourServices:"خدماتنا",contactUs:"اتصل بنا",applications:"التطبيقات الصناعية",applicationsSub:"دعم قطاعات صناعية متنوعة",safeReliable:"السلامة والموثوقية",safeReliableSub:"الاهتمام بالسلامة في كل عملية",trustedSupport:"دعم موثوق",trustedSupportSub:"حلول مبنية حول متطلباتكم",dammam:"الدمام، المملكة العربية السعودية",scroll:"مرر للاستكشاف",who:"من نحن",aboutTitle:"قدرات صناعية.<br><span>تنفيذ حديث.</span>",aboutText:"تدعم شركة نهضة المستقبل للغازات الصناعية المتطلبات الصناعية من خلال التوريد الموثوق والتنسيق المهني ونهج يضع السلامة في المقام الأول.",responsiveSupply:"توريد مرن",responsiveText:"حلول منظمة وفق احتياجات التشغيل واستمرارية الأعمال.",industrialFocus:"تركيز صناعي",focusText:"حلول مناسبة لبيئات العمل والمشاريع والعمليات الإنتاجية.",professionalSupport:"دعم مهني",supportText:"تنسيق واضح من الاستفسار وحتى التوريد والمتابعة.",what:"ماذا نقدم",servicesTitle:"حلول تدفع<br><span>الصناعة إلى الأمام.</span>",gasSolutions:"حلول الغازات الصناعية",gasText:"حلول مهنية للعمليات الصناعية ومتطلبات المشاريع.",supplyDistribution:"التوريد والتوزيع",supplyText:"دعم منظم للتوريد والتوزيع لعملاء الأعمال والقطاع الصناعي.",industrialApps:"التطبيقات الصناعية",appsText:"دعم لأعمال التصنيع والإنشاءات واللحام والأنشطة الصناعية ذات الصلة.",technicalSupport:"الدعم الفني",technicalText:"تنسيق ومساندة عملية تركز على التشغيل الآمن والفعال.",built:"مصمم لخدمة الصناعة",industriesTitle:"شريك واحد.<br><span>تطبيقات متعددة.</span>",fabrication:"التصنيع واللحام",construction:"الإنشاءات",manufacturing:"التصنيع",energy:"الطاقة والمشاريع",safetyTitle:"نهج قائم على<br><span>العمليات المسؤولة.</span>",safetyText:"من المناولة والتنسيق إلى دعم التوريد الصناعي، تظل السلامة والانضباط التشغيلي محوراً أساسياً في طريقة عملنا.",location:"موقعنا · الدمام",a1:"رقم المبنى <strong>7036</strong>، الشارع <strong>45</strong>",a2:"الرقم الفرعي <strong>3313</strong>",a3:"حي الخدمات المساندة",a4:"الرمز البريدي <strong>34354</strong>",build:"نبني المستقبل معاً",finalTitle:"حلول صناعية.<br><span>برؤية مستقبلية.</span>",back:"العودة للأعلى ↑",company:"شركة نهضة المستقبل للغازات الصناعية"}
};
let lang="en";try{lang=localStorage.getItem("nahdat-lang")||"en"}catch(e){}
function setLang(l){lang=l;document.documentElement.lang=l;document.documentElement.dir=l==="ar"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(dict[l][k]!=null)el.textContent=dict[l][k]});document.querySelectorAll("[data-i18n-html]").forEach(el=>{const k=el.dataset.i18nHtml;if(dict[l][k]!=null)el.innerHTML=dict[l][k]});const b=document.getElementById("langSwitch");b.textContent=l==="ar"?"EN":"العربية";try{localStorage.setItem("nahdat-lang",l)}catch(e){}}
document.getElementById("langSwitch").addEventListener("click",()=>setLang(lang==="en"?"ar":"en"));setLang(lang);

const bg=document.getElementById("heroBg"),copy=document.getElementById("heroCopy"),progress=document.getElementById("progress"),addr=document.querySelector(".address-scene"),lines=[...document.querySelectorAll("#addressLines p")];let mx=0,my=0,ticking=false;
function render(){const y=scrollY||0,max=Math.max(1,document.documentElement.scrollHeight-innerHeight);progress.style.width=Math.min(100,y/max*100)+"%";const mobile=innerWidth<801,p=Math.min(1,y/(mobile?700:900));if(bg){const depth=mobile?0.28:0.13;bg.style.transform=`translate3d(${mx*(mobile?18:13)}px,${my*(mobile?13:9)+y*(mobile?.11:.12)}px,0) scale(${(mobile?1.12:1.07)+p*depth})`;bg.style.filter=`brightness(${1-p*.22}) blur(${p*(mobile?.5:1.2)}px)`}if(copy){copy.style.transform=`translate3d(${mx*(mobile?-9:-8)}px,${y*(mobile?.105:.15)}px,${mobile?18:0}px) scale(${1-p*(mobile?.055:.07)})`}const safety=document.querySelector(".safety-panel");if(safety){const r=safety.getBoundingClientRect(),vh=innerHeight;const q=Math.max(0,Math.min(1,(vh-r.top)/(vh+r.height)));const rise=(1-q)*85;const zoom=.87+q*.13;safety.style.transform=`perspective(1100px) translate3d(0,${rise}px,0) rotateX(${(1-q)*5}deg) scale(${zoom})`;safety.style.opacity=String(Math.min(1,.35+q*1.2));safety.style.filter=`blur(${(1-q)*2.5}px)`;}ticking=false}
function req(){if(!ticking){requestAnimationFrame(render);ticking=true}}addEventListener("scroll",req,{passive:true});addEventListener("resize",req);addEventListener("pointermove",e=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5;req()},{passive:true});
let lastTouchY=0;addEventListener("touchstart",e=>{if(e.touches[0])lastTouchY=e.touches[0].clientY},{passive:true});addEventListener("touchmove",e=>{if(e.touches[0]){my=(e.touches[0].clientY-lastTouchY)/innerHeight;req()}},{passive:true});
if(window.DeviceOrientationEvent)addEventListener("deviceorientation",e=>{if(innerWidth<801&&e.gamma!=null){mx=Math.max(-.5,Math.min(.5,e.gamma/60));my=Math.max(-.5,Math.min(.5,(e.beta-45)/90));req()}},{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.1});document.querySelectorAll(".zoom-item:not(.safety-panel)").forEach(x=>io.observe(x));
render();
})();